# Generated by Django 3.2 on 2021-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('temp', models.FloatField()),
                ('vib', models.BooleanField()),
                ('hum', models.IntegerField()),
                ('flam', models.IntegerField()),
                ('intru', models.BooleanField()),
            ],
        ),
    ]
