# Generated by Django 3.2 on 2021-05-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashAdmin',
            new_name='Dash',
        ),
    ]
