# Generated by Django 3.2 on 2021-05-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_dash_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dash',
            name='inc',
            field=models.IntegerField(default=True),
        ),
    ]
