# Generated by Django 3.2 on 2021-05-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dash_inc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='flam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dash',
            name='hum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dash',
            name='inc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dash',
            name='intru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dash',
            name='temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dash',
            name='vib',
            field=models.BooleanField(default=True),
        ),
    ]
