# Generated by Django 3.2 on 2021-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210501_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='temp',
            field=models.FloatField(default=True),
        ),
    ]
